import pool from '../../../lib/db';
import { notFound } from 'next/navigation';

export default async function CaseDocument({ params }) {
  const caseId = params.id;

  let documentData = null;

  try {
    // We query both the docket and the attached document narrative in one shot
    const [rows] = await pool.execute(
      `SELECT d.docket_number, d.case_title, d.defendant_license, d.case_type, 
              DATE_FORMAT(d.filing_date, '%M %d, %Y') as formatted_date,
              doc.document_body, doc.author_identifier 
       FROM arkansas_court_docket d 
       LEFT JOIN arkansas_court_documents doc ON d.case_id = doc.case_id 
       WHERE d.case_id = ? 
       LIMIT 1`,
      [caseId]
    );

    if (rows.length === 0) {
      notFound(); // This triggers the default Next.js 404 page if the case doesn't exist
    }

    documentData = rows[0];

  } catch (error) {
    console.error('Database Fetch Error:', error);
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-200">
        <p className="text-red-700 font-bold text-xl">CRITICAL ERROR: Unable to access judicial mainframe.</p>
      </div>
    );
  }

  // Parse the case title to get the Defendant name (assuming format: "State of Arkansas v. John Doe")
  const defendantName = documentData.case_title.split(' v. ')[1] || 'UNKNOWN';

  return (
    <div className="min-h-screen bg-gray-300 py-10 font-serif text-black flex justify-center">
      
      {/* 8.5x11 aspect ratio simulation */}
      <div className="bg-white w-[816px] min-h-[1056px] shadow-2xl p-16 relative">
        
        {/* Print Only Styles: Hides buttons when users press Ctrl+P */}
        <div className="absolute top-4 right-4 print:hidden">
          <button 
            className="bg-blue-900 text-white px-4 py-2 text-sm font-sans font-bold shadow hover:bg-blue-800"
          >
            PRINT TO PDF
          </button>
        </div>

        {/* File Stamp Area (Top Right) */}
        <div className="flex justify-end mb-8 h-16">
          <div className="text-xs text-right border-2 border-red-700 p-2 text-red-700 font-bold uppercase w-48 transform -rotate-2 opacity-80">
            FILED <br />
            PULASKI CIRCUIT CLERK <br />
            {documentData.formatted_date} <br />
            By: AOC Auto-File System
          </div>
        </div>

        {/* Court Header */}
        <div className="text-center font-bold text-lg mb-10 tracking-wide">
          IN THE DISTRICT COURT OF PULASKI COUNTY, ARKANSAS
        </div>

        {/* Case Parties Block */}
        <div className="flex justify-between items-stretch border-b-2 border-black pb-8 mb-8">
          <div className="w-1/2 flex flex-col justify-between">
            <div className="font-bold uppercase">STATE OF ARKANSAS</div>
            <div className="italic my-4">VS.</div>
            <div className="font-bold uppercase">{defendantName}</div>
          </div>
          <div className="w-1/2 flex flex-col justify-center pl-8 border-l border-gray-400">
            <div className="font-bold text-xl mb-2 text-gray-800">CASE NO. {documentData.docket_number}</div>
            <div className="font-bold uppercase tracking-widest">{documentData.case_type} DIVISION</div>
          </div>
        </div>

        {/* Document Body */}
        <div className="leading-relaxed text-justify space-y-6">
          <div className="font-bold text-lg underline mb-2">FACTUAL BASIS / AFFIDAVIT:</div>
          <div className="whitespace-pre-wrap">{documentData.document_body || "No affidavit attached to this docket."}</div>
        </div>

        {/* Signature Block */}
        <div className="mt-24 flex justify-end">
          <div className="w-64 text-center">
            <div className="border-b border-black mb-2 h-8"></div>
            <div className="font-bold uppercase">{documentData.author_identifier}</div>
            <div className="text-sm italic">Digitally Signed / E-Filed</div>
          </div>
        </div>

        {/* Footer */}
        <div className="absolute bottom-10 left-0 right-0 text-center text-xs text-gray-500">
          Generated by ASRP CourtConnect CMS • Official Record • Document ID: {caseId}
        </div>

      </div>
    </div>
  );
}